In [1]:
import pandas as pd

df = pd.read_csv('rolex.v1.txt', sep='\t', header=None, names=['word_form', 'lemma', 'MSD_tag', 'syllabification', 'lexical_stress', 'phonetic_transcription'])

df.head(50)

,word_form,lemma,MSD_tag,syllabification,lexical_stress,phonetic_transcription
0,Ăstea,acesta,Dd3fpr---o,ăs.tea,'ăstea,@ s t e_X a
1,ă,=,I,ă,ă,@
2,ăi,acel,Dd3mpr---e,ăi,ăi,@ j
3,ăi,acela,Pd3mpr,ăi,ăi,@ j
4,ăi,vrea,Va--2s,ăi,ăi,@ j
5,ăia,acela,Dd3mpr---o,ă.ia,'ăia,@ i a
6,ăia,acela,Pd3mpr,ă.ia,'ăia,@ i a
7,ăl,acel,Dd3msr---e,ăl,ăl,@ l
8,ăl,cel,Tdmsr,ăl,ăl,@ l
9,ăla,acela,Dd3msr---o,ă.la,'ăla,@ l a
10,ăla,acela,Pd3msr,ă.la,'ăla,@ l a
11,ălei,acel,Dd3fso---e,ă.lei,'ălei,@ l e j
12,ăleia,acela,Dd3fso---o,ă.le.ia,'ăleia,@ l e j a
13,ăleia,acela,Pd3fso,ă.le.ia,'ăleia,@ l e j a
14,ălor,acel,Dd3-po---e,ă.lor,'ălor,@ l o r
15,ălora,acela,Dd3-po---o,ă.lo.ra,'ălora,@ l o r a
16,ălora,acela,Pd3-po,ă.lo.ra,'ălora,@ l o r a
17,ălorlalți,celălalt,Dd3mpo,ă.lor.lalți,'ălorlalți,@ l o r l a l ts i_0
18,ălorlalți,celălalt,Pd3mpo,ă.lor.lalți,'ălorlalți,@ l o r l a l ts i_0
19,ălui,acel,Dd3mso---e,ă.lui,'ălui,@ l u j
20,ăluia,acela,Dd3mso---o,ă.lu.ia,'ăluia,@ l u j a
21,ăluia,acela,Pd3mso,ă.lu.ia,'ăluia,@ l u j a
22,ălălalt,celălalt,Dd3msr,ă.lă.lalt,'ălălalt,@ l @ l a l t
23,ălălalt,celălalt,Pd3msr,ă.lă.lalt,'ălălalt,@ l @ l a l t
24,ăst,acest,Dd3msr---e,ăst,ăst,@ s t
25,ăsta,acesta,Dd3msr---o,ăs.ta,'ăsta,@ s t a
26,ăsta,acesta,Pd3msr,ăs.ta,'ăsta,@ s t a
27,ăstalalt,=,Dd3msr,ăs.ta.lalt,'ăstalalt,@ s t a l a l t
28,ăstalalt,=,Pd3msr,ăs.ta.lalt,'ăstalalt,@ s t a l a l t
29,ăstei,acest,Dd3fso---e,ăs.tei,'ăstei,@ s t e j
30,ăsteia,acesta,Dd3fso---o,ăs.te.ia,'ăsteia,@ s t e j a
31,ăsteia,acesta,Pd3fso,ăs.te.ia,'ăsteia,@ s t e j a
32,ăsteilalte,ăstalalt,Dd3fso,ăs.tei.lal.te,'ăsteilalte,@ s t e j l a l t e
33,ăsteilalte,ăstalalt,Pd3fso,ăs.tei.lal.te,'ăsteilalte,@ s t e j l a l t e
34,ăstor,acest,Dd3-po---e,ăs.tor,'ăstor,@ s t o r
35,ăstora,acesta,Dd3-po---o,ăs.to.ra,'ăstora,@ s t o r a
36,ăstora,acesta,Pd3-po,ăs.to.ra,'ăstora,@ s t o r a
37,ăstorlalte,ăstalalt,Dd3fpo,ăs.tor.lal.te,'ăstorlalte,@ s t o r l a l t e
38,ăstorlalte,ăstalalt,Pd3fpo,ăs.tor.lal.te,'ăstorlalte,@ s t o r l a l t e
39,ăstorlalți,ăstalalt,Dd3mpo,ăs.tor.lalți,'ăstorlalți,@ s t o r l a l ts i_0
40,ăstorlalți,ăstalalt,Pd3mpo,ăs.tor.lalți,'ăstorlalți,@ s t o r l a l ts i_0
41,ăstui,acest,Dd3mso---e,ăs.tui,'ăstui,@ s t u j
42,ăstuia,acesta,Dd3mso---o,ăs.tu.ia,'ăstuia,@ s t u j a
43,ăstuia,acesta,Pd3mso,ăs.tu.ia,'ăstuia,@ s t u j a
44,ăstuilalt,ăstalalt,Dd3mso,ăs.tui.lalt,'ăstuilalt,@ s t u j l a l t
45,ăstuilalt,ăstalalt,Pd3mso,ăs.tui.lalt,'ăstuilalt,@ s t u j l a l t
46,ăști,acest,Dd3mpr---e,ăști,ăști,@ S t i_0
47,ăștia,acesta,Dd3mpr---o,ăș.tia,'ăștia,@ S t j a
48,ăștia,acesta,Pd3mpr,ăș.tia,'ăștia,@ S t j a
49,ăți,vrea,Va--2p,ăți,'ăți,@ ts i_0

In [2]:
metadata = pd.read_csv('../ro_vsr/metadata_ready.csv')
duration_df = pd.read_csv('../ro_vsr/metadata_clean.csv', usecols=['file_path', 'duration'])
duration_df = duration_df.drop_duplicates(subset='file_path', keep='first')
metadata = metadata.merge(duration_df, left_on='clip_path', right_on='file_path', how='left')
metadata = metadata.drop(columns=['file_path'])

In [3]:
import os

def lookup_token(token, word_form_index):
    # Try exact match
    if token in word_form_index:
        return word_form_index[token]
    # Try lowercasing the token
    if token.lower() in word_form_index:
        return word_form_index[token.lower()]
    # Try capitalizing first char of token
    capitalized = token[0].upper() + token[1:] if token else token
    if capitalized in word_form_index:
        return word_form_index[capitalized]
    return None

def lookup_token_with_hyphen(token, word_form_index):
    # First try direct lookup (all casing variants)
    result = lookup_token(token, word_form_index)
    if result is not None:
        return result

    # If hyphenated, split and look up each part
    if '-' in token:
        parts = token.split('-')
        phoneme_parts = []
        for part in parts:
            if not part:  # skip empty from leading/trailing hyphens
                continue
            p = lookup_token(part, word_form_index)
            if p is None:
                return None  # any part missing -> whole token fails
            phoneme_parts.append(p)
        if phoneme_parts:
            return ' '.join(phoneme_parts)
    return None

# Build phoneme index from rolex (keep='last' to prefer common POS entries)
word_form_index = df.drop_duplicates('word_form', keep='last').set_index('word_form')['phonetic_transcription'].to_dict()

# Load manual entries for frequent missing words
extra = pd.read_csv('frequent_missing.tsv', sep='\t', header=None,
                     names=['word_form', 'lemma', 'MSD_tag', 'syllabification', 'lexical_stress', 'phonetic_transcription'])
word_form_index.update(extra.drop_duplicates('word_form').set_index('word_form')['phonetic_transcription'].to_dict())

# Load LLM-generated entries (from fill_unk.ipynb)
llm_file = 'llm_generated_missing.tsv'
n_llm = 0
if os.path.exists(llm_file):
    llm_extra = pd.read_csv(llm_file, sep='\t', header=None,
                             names=['word_form', 'lemma', 'MSD_tag', 'syllabification', 'lexical_stress', 'phonetic_transcription'])
    word_form_index.update(llm_extra.drop_duplicates('word_form').set_index('word_form')['phonetic_transcription'].to_dict())
    n_llm = len(llm_extra)

print(f"Phoneme index: {len(word_form_index)} entries (rolex + {len(extra)} manual + {n_llm} LLM)")
print(f"  și -> {word_form_index.get('și')}")
print(f"  e  -> {word_form_index.get('e')}")

Phoneme index: 284277 entries (rolex + 15 manual + 11953 LLM)
  și -> S i
  e  -> je

In [4]:
from collections import Counter

UNK = 'UNK'

def phonemize_sentence(transcript, word_form_index):
    tokens = transcript.split()
    phoneme_list = []
    n_missing = 0
    max_consecutive = 0
    current_consecutive = 0
    for token in tokens:
        phonemes = lookup_token_with_hyphen(token, word_form_index)
        if phonemes is not None:
            phoneme_list.append(phonemes)
            current_consecutive = 0
        else:
            phoneme_list.append(UNK)
            n_missing += 1
            current_consecutive += 1
            max_consecutive = max(max_consecutive, current_consecutive)
    return phoneme_list, n_missing, max_consecutive, len(tokens)

# Process all sentences
results = []
for _, row in metadata.iterrows():
    transcript = row['transcript']
    if pd.isna(transcript):
        continue
    phoneme_list, n_missing, max_consecutive, n_tokens = phonemize_sentence(transcript, word_form_index)
    missing_ratio = n_missing / n_tokens if n_tokens else 0
    results.append({
        'clip_path': row['clip_path'],
        'transcript': transcript,
        'phonemes': ' '.join(phoneme_list),
        'n_tokens': n_tokens,
        'n_missing': n_missing,
        'missing_ratio': missing_ratio,
        'max_consecutive_missing': max_consecutive,
        'split': row.get('split', ''),
        'duration': row.get('duration', float('nan')),
    })

results_df = pd.DataFrame(results)

# Drop: > 1/3 missing tokens OR >= 2 consecutive missing
drop_high_missing = results_df['missing_ratio'] > 1/3
drop_consecutive = results_df['max_consecutive_missing'] >= 2
drop_mask = drop_high_missing | drop_consecutive
clean_df = results_df[~drop_mask].copy()

# Coverage stats
token_counts = Counter(token for t in metadata['transcript'].dropna() for token in t.split())
total_occ = sum(token_counts.values())
matched_occ = sum(c for t, c in token_counts.items() if lookup_token_with_hyphen(t, word_form_index) is not None)

print(f"Absolute token coverage: {matched_occ/total_occ:.2%}")
print(f"Total sentences: {len(results_df)}")
print(f"Dropped (>33% missing): {drop_high_missing.sum()} ({drop_high_missing.mean():.2%})")
print(f"Dropped (≥2 consecutive missing): {drop_consecutive.sum()} ({drop_consecutive.mean():.2%})")
print(f"Dropped (either): {drop_mask.sum()} ({drop_mask.mean():.2%})")
print(f"Kept: {len(clean_df)} ({(~drop_mask).mean():.2%})")
print(f"  Fully phonemized: {(clean_df['n_missing'] == 0).sum()}")
print(f"  With UNK: {(clean_df['n_missing'] > 0).sum()}")

Absolute token coverage: 99.98%
Total sentences: 39929
Dropped (>33% missing): 1 (0.00%)
Dropped (≥2 consecutive missing): 8 (0.02%)
Dropped (either): 8 (0.02%)
Kept: 39921 (99.98%)
  Fully phonemized: 39773
  With UNK: 148

In [5]:
results_df = results_df[~results_df['phonemes'].str.contains(r'\bUNK\b', regex=True, case=True)]
len(results_df)

39773

In [6]:
from pathlib import Path

clips_dir = Path('../clips')

existing_clips = {path.stem for path in clips_dir.rglob('*.avi')}

results_df = results_df[results_df['clip_path'].isin(existing_clips)]

len(results_df)

39660

In [7]:
results_df = results_df[results_df['duration'] <= 30].copy()
fin_df = results_df[['clip_path', 'transcript', 'phonemes', 'split']]
fin_df.to_csv('../labels.csv', index=False)

split_lengths = results_df.groupby('split')['duration'].sum().sort_values(ascending=False)

print('Split lengths after all filtering:')
for split_name, total_seconds in split_lengths.items():
    print(f"{split_name}: {total_seconds / 3600:.2f}h ({total_seconds / 60:.2f}m)")

fin_df.head(50)

Split lengths after all filtering:
train: 100.45h (6026.94m)
val: 11.25h (674.89m)
test: 10.33h (619.50m)

,clip_path,transcript,phonemes,split
0,andreea_antonescu_qahn56pteSA_clip_238,că au avut ceva de învățat de aici și sigur da...,k @ a w a v u t tS e v a d e 1 n v @ ts a t d ...,train
1,bianca_nutu_4QMZpa_zYKU_clip_81,ceea ce gândești ceea ce simți despre ceea ce ...,tS e e_X a tS e g 1 n d e S t i_0 tS e e_X a t...,train
2,iulia_parlea_AMpklgShYD0_clip_279,maică-mea avea o chestie cu mințitul deci ea d...,m a j k @ m e_X a a v e_X a o k_j e s t i e k ...,train
3,ana_morodan_aDOzKnPltgw_clip_210,tinerilor care au probleme din zona digitală,t i n e r i l o r k a r e a w p r o b l e m e ...,train
4,lolrelai_sCOjyP2ZdJo_clip_400,doi la mână eu am aflat că nu s-au luat camere...,d o j l a m 1 n @ e w a m a f l a t k @ n u s ...,train
5,irina_petrea_CO4P03D_Hl0_clip_190,dar fără să fiu foarte insistent dacă refuză s...,d a r f @ r @ s @ f i w f o_X a r t e i n s i ...,train
6,ioana_ginghina_WC5SA66nEIY_clip_68,cei doi clooney și cu brad pitt frumoși așa ș...,tS e j d o j k l u n i S i k u b r a d p i t f...,train
7,mihaela_tatu_kD4lJehL23Q_clip_291,nu nu seara înainte de culcare îi mulțumesc pe...,n u n u s e_X a r a 1 n a j n t e d e k u l k ...,train
8,adrian_alexandrov_G1h5PBrtzds_clip_85,nu pe mine personal nu toți prietenii mei sunt...,n u p e m i n e p e r s o n a l n u t o ts i_0...,train
9,catalin_bordea_zlRnts0-FWg_clip_179,mă știu de foarte mult timp cu ei dar acum noi...,m @ S t i u d e f o_X a r t e m u l t t i m p ...,train
10,florin_calinescu_iBwD73xt_yEc_clip_418,la cine dacă așa a vrut dumnezeu de ce să mă a...,l a tS i n e d a k @ a S a a v r u t d u m n e...,train
11,rares_banescu_VMc9Zid0PfU_clip_62,nu știu să zic așa sunt am un simț al lucrului...,n u S t i u s @ z i k a S a s u n t a m u n s ...,train
12,jador_Zf2VAPvFKBY_clip_84,bă și m-am m-am înscris și m-o sunat nu vrei s...,b @ S i m a m m a m 1 n s k r i s S i m o s u ...,train
13,denisa_tanase_ssHHgjQJ60s_clip_350,păi nu n-aveau cum să aibă încredere că eram u...,p @ j n u n a v e_X a w k u m s @ a j b @ 1 n ...,train
14,narcisa_suciu_bDs0K1ohnnA_clip_30,dar și am făcut-o mă rog cum am priceput și cu...,d a r S i a m f @ k u t o m @ r o g k u m a m ...,train
15,maria_popovici_kbFDprbpSGE_clip_124,le-ai spus nu le-am bifat niciuna n-a fost nic...,l e a j s p u s n u l e a m b i f a t n i tS u...,train
16,mihai_sturzu_zkCC5Iprutk_clip_136,soare bucurie căldură ne-am oprit noi ne-am ...,s o_X a r e b u k u r i e k @ l d u r @ n e a ...,train
17,pavel_bartos_gb0LdjOrfrA_clip_279,de puteri erau numai scutece și că de asta zic...,d e p u t e r i_0 e r a w n u m a j s k u t e ...,train
18,constantin_cornea_pd4MvRbSwaI_clip_70,hără hei asta fac de dimineață până seara de u...,h @ r @ h e j a s t a f a k d e d i m i n e_X ...,train
19,costin_damasaru_AKixW6npsdw_clip_396,evoluat elevat și va ajuta și pe ei să evoluez...,e v o l u a t e l e v a t S i v a a Z u t a S ...,train
20,minodora_9e3UrrGYyTg_clip_352,și m-au atras degetele lui mâinile c-are mâini...,S i m a w a t r a s d e gZ e t e l e l u j m 1...,train
21,catalin_morosanu_cHZtx32dtDg_clip_76,și eu dacă lucrul ăsta mi l-am creat în în cre...,S i e w d a k @ l u k r u l @ s t a m i l a m ...,train
22,catalin_bordea_zlRnts0-FWg_clip_98,și tot timpul o să vină după voi fără să le ch...,S i t o t t i m p u l o s @ v i n @ d u p @ v ...,train
23,iustinian_simion_FEamYElBGxg_clip_198,am crezut că se sfârșește lumea în momentul re...,a m k r e z u t k @ s e s f 1 r S e S t e l u ...,train
24,mihai_craiu_SIslEeHmoT8_clip_52,copilul primește toate aceste semnale transpla...,k o p i l u l p r i m e S t e t o_X a t e a tS...,train
25,ramona_olaru_YLsz_G6DCbI_clip_158,e un detaliu pentru pe despre care oamenii hab...,je u n d e t a l j u p e n t r u p e d e s p r...,train
26,dan_alexa_PzILbYw-3h8_clip_21,rucsacurile în spatele era clar că e o emisiun...,r u k s a k u r i l e 1 n s p a t e l e e r a ...,train
27,radu_fornea_NbMpkNOu1BQ_clip_73,poate că roboți industriali evident și acolo a...,p o_X a t e k @ r o b o ts i_0 i n d u s t r j...,train
28,iuliana_beregoi_74uJ0Mt7VQg_clip_491,foarte multă muzică veche ascult în rusă ascul...,f o_X a r t e m u l t @ m u z i k @ v e k_j e ...,train
29,bianca_nutu_4QMZpa_zYKU_clip_271,nează fie că se întâlnesc cu cineva cu un stră...,n e a z @ f i e k @ s e 1 n t 1 l n e s k k u ...,train
30,flick_MfbPvQLQv54_clip_153,încercam să spun că noi facem totul împreună c...,1 n tS e r k a m s @ s p u n k @ n o j f a tS ...,train
32,marian_dragulescu_VbeiBvjKprQ_clip_191,cum a trecut și timpul așa cum mă uit înapoi î...,k u m a t r e k u t S i t i m p u l a S a k u ...,train
33,denisa_filcea_C9AdvwpOgUI_clip_79,nu a fost pentru dat fiind faptul că s-a și de...,n u a f o s t p e n t r u d a t f i i n d f a ...,train
34,valeriu_panoiu_yh1VdmlyFbQ_clip_217,ajungă la un punct zero s-ar putea ca și număr...,a Z u n g @ l a u n p u n k t z e r o s a r p ...,train
35,suada_agachi_IcFx976GqiQ_clip_278,altfel îți axezi discursul știi cu alți oameni...,a l t f e l 1 ts i_0 a ks e z i_0 d i s k u r ...,train
36,razvan_fodor_V4f0-TjfZAE_clip_56,eram eu cu maică-mea si taică-miu erau tot ti...,e r a m e w k u m a j k @ m e_X a s i t a j k ...,train
37,anca_biris_OzEDDtKqCkk_clip_236,odată și după ce am mă rog am lucrat a- a,o d a t @ S i d u p @ tS e a m m @ r o g a m l...,train
38,meme_stoica_llN2G6QrCgI_clip_277,cât de buni să știa sau de ieri cred că vorbea...,k 1 t d e b u n i_0 s @ S t i a s a w d e j e ...,train
39,bianca_nutu_4QMZpa_zYKU_clip_345,aici mă refer mai ales când vorbim de astrolog...,a i tS m @ r e f e r m a j a l e s k 1 n d v o...,train
40,oana_ionita_dJCwR14g75s_clip_20,mai mulți prieteni și-au zis aa păi dar tu ai ...,m a j m u l ts i_0 p r i e t e n i_0 S i a w z...,train
41,rux_opulenta_DYdtJZ_XJsw_clip_214,păi să le vină da sunt altele pe listă care se...,p @ j s @ l e v i n @ d a s u n t a l t e l e ...,train
42,iuliana_beregoi_74uJ0Mt7VQg_clip_139,ofer tot într-o prietenie mă deschid complet s...,o f e r t o t 1 n t r o p r i e t e n i e m @ ...,train
43,catalin_morosanu_cHZtx32dtDg_clip_171,ca toate lucrurile să fie ok pe pe toate planu...,k a t o_X a t e l u k r u r i l e s @ f i e o ...,train
44,alina_ceusan_w0HBEzBk5ac_clip_121,să crească împreună și mai mulți să se bucure ...,s @ k r e_X a s k @ 1 m p r e u n @ S i m a j ...,train
45,iancu_guda_aYFt5grEg1Q_clip_17,rămâneau acolo nu că n-aveau ce să facă dar da...,r @ m 1 n e_X a w a k o l o n u k @ n a v e_X ...,train
46,oana_ionita_dJCwR14g75s_clip_160,dar am simțit că îmi era cel mai mare dușman ș...,d a r a m s i m ts i t k @ 1 m i_0 e r a tS e ...,train
47,larisa_uta_4PFoJQ1k8-U_clip_397,niște copii care nu știu ce ia urățenie n-au t...,n i S t e k o p i j k a r e n u S t i u tS e j...,train
48,andreea_ibacka_L2roW3KzrSE_clip_89,și noi eram unul lângă celălalt fiecare cu gân...,S i n o j e r a m u n u l l 1 n g @ tS e l @ l...,train
49,silviu_prigoana_a0XSasBfUPE_clip_46,otoman noi nu am fost parte cu ei acolo păi da...,o t o m a n n o j n u a m f o s t p a r t e k ...,train
50,calin_donca_cGV6VbXBCIc_clip_31,ani doi ani în care o companie românească în d...,a n i_0 d o j a n i_0 1 n k a r e o k o m p a ...,train